### PR TITLE
Changed Game Exit to L+HOME and Buttons Swap to L+MINUS to prevent confusion

### PR DESCRIPTION
**Pull request by Raflos10**
Wii U Gamepad and BT controllers:
Buttons Swap: L+MINUS
Game Exit: L+HOME
Wii Remotes:
Game Exit: 2+HOME

### CODE REVIEW

**Comment by arturogakaxy** [comment]
Or maybe holding the mentioned buttons for 1 second (if its possible to implement that) to keep simplicity and improve security.

**Comment by Raflos10** [comment]
I like that idea. It would work great for game exit, because people could figure it out without the need to google it. 
I don't think it would work well for the button swap. Although button swap feature itself is sort of weak since you have to activate it every time you launch a game if the alternate controls are your preference. The ultimate solution here would be to have a button mapping feature in the launcher that allows you to set up the default mapping for each controller. And maybe additional mappings you can cycle through. If I ever have some time on my hands (this summer maybe?) I'll work on creating a nice feature like that.
In the mean time yeah, I'll throw in a button timer when I get a chance.

**Comment by GerbilSoft** [comment]
I implemented a 2-second HOME button delay a while back in a branch but never got around to sending a PR: https://github.com/GerbilSoft/Nintendont/tree/delay-home-button

It's from two years ago, so it'll probably need to be updated manually.

**Comment by Raflos10** [comment]
Excellent thank you!

**Comment by arturogakaxy** [comment]
Thats works great! altought I think 2 seconds is a bit too much, I would set 0.8-1 seconds, just like the power / shut down button of wii and controllers. Would be nice to have this implemented into an updated nintendont!

**Pull request closed without merging**
