### PR TITLE
CISO, MD5, cache fixes, and others

### PR DESCRIPTION
**Pull request by GerbilSoft**
Here's my widescreen-hax.r422 branch. It was originally named widescreen-hax.r422 because it had some optimizations for widescreen (namely the Nintendont wallpaper aspect ratio and some optimizations for the static widescreen switch/case), but I got a bit distracted and did a bunch of other stuff.

Major changes:
* Rebased FatFS to R0.12b_p1.
* Added support for CISO-format disc images. The kernel-side implementation is all in ISO.c; the rest of the kernel doesn't know or care about CISO.
* Significantly improved multi-game disc image handling. Multi-game disc images larger than 4 GB now work (on exFAT partitions). DVD-Rs still seem to have some crashing issues.
* Use the bi2.bin region code instead of the Game ID region. This improves region handling for prototype games with the game ID "RELSAB", e.g. the Sonic Adventure DX Preview prototype.

Loader-specific changes:
* Replaced the simple caching code with a version of libfat's caching code. libfat's cache implements write-back caching, while the old code simply discarded cached sectors on write, and could only cache sectors if a single sector was read in. This appears to fix the memory card creation lag several users were reporting.
* The background wallpaper is now adjusted for widescreen aspect ratio if the system widescreen setting is enabled.
* Rewrote a good chunk of the menu code to be more flexible.
* Games no longer have to be in a subdirectory under /games/. Any *.iso, *.gcm, *.cso, or *.ciso file in /games/ will be detected. 2-disc games still need subdirectories, but any of those four file extensions can be used instead of just *.iso.
* The game list now colorizes games based on their format. A color legend is displayed underneath the firmware version.
* Improved key repeat handling.
* Grayed out items in the Settings menu that don't apply to the current system. For example, "Native Control" is grayed out on Wii U.
* Added descriptions for some of the items in the Settings menu.
* Optimized memory card formatting and reduced memory usage. Instead of allocating a full card, it now only allocates 64 KB.
* Memory card initialization now shows a progress screen. This was added prior to the libfat cache code in order to diagnose why the card creation was slow, but I didn't remove it because I think it's still useful.
* Added an MD5 verifier. This requires a database file gcn_md5.txt, located in the repository as /nintendont/gcn_md5.zip (requires decompression). The file has been added to the built-in updater and is automatically decompressed on download. (The MD5 verifier is only enabled for 1:1 images. If any other format is selected, the MD5 verifier is disabled and grayed out.)

Other changes:
* Replaced the build system with Makefiles. Build.sh/Build.bat are still present, but they simply call `make`.

### CODE REVIEW

**Comment by GerbilSoft** [comment]
I just noticed that I left the update URL for gcn_md5.zip set to my repository instead of the main one because I was using that for testing. It's not a big deal, but it should be changed back later.

**Comment by GerbilSoft** [comment]
There seems to be an issue with the MD5 verifier (at least on my system) where the first time I run it, it goes up to 280 MB, then fails and returns back to the game list. Running it again works. I'm not sure why; this will need further debugging, but it should still be good enough to merge now.

**Comment by GerbilSoft** [comment]
Fixed the MD5 verifier issue. diskio.c previously re-read up to 10 times on errors (for USB only), but the libfat cache code didn't. The libfat cache code now re-reads up to 10 times on errors regardless of device.

Tested with SA2B and it verified correctly.

**Comment by rattboi** [comment]
Awesome

**Pull request merged**
