### PR TITLE
GPT Support v3: Ignore EFI System Partition; support MBR extended; code optimizations

### PR DESCRIPTION
**Pull request by GerbilSoft**
This pull request fixes an issue caused by Mac OS X adding an EFI System Partition to Hybrid GPT devices in some cases. The EFI System Partition is formatted as FAT32, which trips up Nintendont's partition search because it assumes the first FAT partition on the drive is the Nintendont partition. To work around this, partitions with the EFI System Partition GUID {C12A7328-F81F-11D2-BA4B-00A0C93EC93B} are now ignored.

(rebased from gpt-support-v3 to remove redundant recompiles)

Some other changes in this pull request:
* Rebased to FatFS R0.12_p3. This has support for exFAT, but it's currently disabled because the loader doesn't support it. (A possible workaround is to rewrite the loader to use FatFS instead of libcustomfat.)
* Added support for MBR extended partitions in the kernel. libcustomfat supported this, which led to the confusing situation of the loader showing a game list and then crashing when trying to load the kernel. Note that only type 0x0F is supported. (Linux fdisk and gparted create extended partitions with type 0x05 for some reason.)
* Optimized some code segments. I ran into an issue caused by the switch to -O3 where the .text segment outgrew its allotted memory area. Instead of increasing the size of the .text section, I optimized a few areas of the code.

### CODE REVIEW

**Comment by GerbilSoft** [comment]
Tagging issues that this should fix: #202, #242

**Comment by FIX94** [comment]
why did you change a clear32 to a set32 in diskio.c? that seems like a mistake to me.

**Comment by GerbilSoft** [comment]
Yeah, that's a rebase error. Fixed now.

**Comment by FIX94** [comment]
nice, I guess later today I'll get to work starting to port that fatfs module over to the loader as well, will probably take quite a bit of time.

**Comment by GerbilSoft** [comment]
FYI: I didn't update the version number, so you might want to do that. (I should probably update the version number in future PRs.)

**Pull request merged**
