### PR TITLE
Support configuring Wii U Gamepad controller slot.

### PR DESCRIPTION
**Pull request by sailormoon**
Instead of defaulting to player 1, allow it be configurable and swapped to other ports or even disabled.

### CODE REVIEW

**Comment by sailormoon** [comment]
@carnage702 I really appreciate all your work on this project. Let me know if you want anything changed or if I can help out in any way!

**Comment by carnage702** [comment]
hey there is a bug here  if you use the ps3 controller which is diferent call from hid and gamepad is in slot one, even if you dont use the gamepad the ps3 controller has no controlls and doesnt get moved up not even in nintendont menu, i think you forgot to se the ps3 pad which has diferent functions on the order list

**Comment by carnage702** [comment]
> 
> 
> @carnage702 I really appreciate all your work on this project. Let me know if you want anything changed or if I can help out in any way!



hey there is a bug here if you use the ps3 controller which is diferent call from hid and gamepad is in slot one, even if you dont use the gamepad the ps3 controller has no controlls and doesnt get moved up not even in nintendont menu, i think you forgot to se the ps3 pad which has diferent functions on the order list

**Comment by carnage702** [comment]
> 
> 
> @carnage702 I really appreciate all your work on this project. Let me know if you want anything changed or if I can help out in any way!

i managed to fix the solo hid ps3 issue but now there is a new issue when using wiiu injects the ones that autoboot the gamepad does not work, becuase the autoboot skips the menu and the variable of wiiugamepadslot never gets the correct value, while vwii injects that load nintendont menu to choose a game from work just fine with wiiu gamepad.

**Pull request merged**
